-- countries.intl_zone: страна -> тарифная зона (официальная таблица Казпочты).
-- Источник -- прикреплённые изображения (2 стр. таблицы "страна -> зона"); Армения
-- намеренно не заполнена (зона не читается уверенно на исходной картинке).

-- Существующие страны (обновление зоны)
UPDATE countries SET intl_zone = '2' WHERE iso2 = 'AZ';
UPDATE countries SET intl_zone = '1' WHERE iso2 = 'BY';
UPDATE countries SET intl_zone = '3' WHERE iso2 = 'GB';
UPDATE countries SET intl_zone = '3' WHERE iso2 = 'DE';
UPDATE countries SET intl_zone = '4' WHERE iso2 = 'CN';
UPDATE countries SET intl_zone = '1' WHERE iso2 = 'KG';
UPDATE countries SET intl_zone = '3' WHERE iso2 = 'MD';
UPDATE countries SET intl_zone = '4' WHERE iso2 = 'AE';
UPDATE countries SET intl_zone = '2' WHERE iso2 = 'RU';
UPDATE countries SET intl_zone = '4' WHERE iso2 = 'US';
UPDATE countries SET intl_zone = '1' WHERE iso2 = 'TJ';
UPDATE countries SET intl_zone = '3' WHERE iso2 = 'TR';
UPDATE countries SET intl_zone = '1' WHERE iso2 = 'UZ';

-- Новые страны (добавление; shipping_zone='INTERNATIONAL' -- ни одна не входит в
-- существующий список СНГ/Казахстан)
INSERT INTO countries (iso2, name_ru, name_en, shipping_zone, intl_zone, active) VALUES
('AU', 'Австралия', 'Australia', 'INTERNATIONAL', '5', true),
('AT', 'Австрия', 'Austria', 'INTERNATIONAL', '3', true),
('AL', 'Албания', 'Albania', 'INTERNATIONAL', '3', true),
('DZ', 'Алжир', 'Algeria', 'INTERNATIONAL', '5', true),
('AI', 'Ангилья', 'Anguilla', 'INTERNATIONAL', '5', true),
('AO', 'Ангола', 'Angola', 'INTERNATIONAL', '5', true),
('AG', 'Антигуа и Барбуда', 'Antigua and Barbuda', 'INTERNATIONAL', '5', true),
('AR', 'Аргентина', 'Argentina', 'INTERNATIONAL', '5', true),
('AW', 'Аруба', 'Aruba', 'INTERNATIONAL', '5', true),
('AF', 'Афганистан', 'Afghanistan', 'INTERNATIONAL', '4', true),
('BS', 'Багамы', 'Bahamas', 'INTERNATIONAL', '5', true),
('BD', 'Бангладеш', 'Bangladesh', 'INTERNATIONAL', '4', true),
('BB', 'Барбадос', 'Barbados', 'INTERNATIONAL', '5', true),
('BH', 'Бахрейн', 'Bahrain', 'INTERNATIONAL', '4', true),
('BZ', 'Белиз', 'Belize', 'INTERNATIONAL', '5', true),
('BE', 'Бельгия', 'Belgium', 'INTERNATIONAL', '3', true),
('BJ', 'Бенин', 'Benin', 'INTERNATIONAL', '5', true),
('BM', 'Бермуды', 'Bermuda', 'INTERNATIONAL', '5', true),
('BG', 'Болгария', 'Bulgaria', 'INTERNATIONAL', '3', true),
('BO', 'Боливия', 'Bolivia', 'INTERNATIONAL', '5', true),
('BA', 'Босния и Герцеговина', 'Bosnia and Herzegovina', 'INTERNATIONAL', '3', true),
('BW', 'Ботсвана', 'Botswana', 'INTERNATIONAL', '5', true),
('BR', 'Бразилия', 'Brazil', 'INTERNATIONAL', '5', true),
('BN', 'Бруней', 'Brunei', 'INTERNATIONAL', '5', true),
('BF', 'Буркина-Фасо', 'Burkina Faso', 'INTERNATIONAL', '5', true),
('BI', 'Бурунди', 'Burundi', 'INTERNATIONAL', '5', true),
('BT', 'Бутан', 'Bhutan', 'INTERNATIONAL', '4', true),
('VU', 'Вануату', 'Vanuatu', 'INTERNATIONAL', '5', true),
('VA', 'Ватикан', 'Vatican', 'INTERNATIONAL', '3', true),
('HU', 'Венгрия', 'Hungary', 'INTERNATIONAL', '3', true),
('VE', 'Венесуэла', 'Venezuela', 'INTERNATIONAL', '5', true),
('VG', 'Виргинские о-ва (Британские)', 'British Virgin Islands', 'INTERNATIONAL', '5', true),
('VN', 'Вьетнам', 'Vietnam', 'INTERNATIONAL', '4', true),
('GA', 'Габон', 'Gabon', 'INTERNATIONAL', '5', true),
('HT', 'Гаити', 'Haiti', 'INTERNATIONAL', '5', true),
('GM', 'Гамбия', 'Gambia', 'INTERNATIONAL', '5', true),
('GH', 'Гана', 'Ghana', 'INTERNATIONAL', '5', true),
('GP', 'Гваделупа', 'Guadeloupe', 'INTERNATIONAL', '5', true),
('GT', 'Гватемала', 'Guatemala', 'INTERNATIONAL', '5', true),
('GN', 'Гвинея', 'Guinea', 'INTERNATIONAL', '5', true),
('GW', 'Гвинея-Бисау', 'Guinea-Bissau', 'INTERNATIONAL', '5', true),
('GI', 'Гибралтар', 'Gibraltar', 'INTERNATIONAL', '5', true),
('HN', 'Гондурас', 'Honduras', 'INTERNATIONAL', '5', true),
('HK', 'Гонконг (Китай)', 'Hong Kong', 'INTERNATIONAL', '4', true),
('GD', 'Гренада', 'Grenada', 'INTERNATIONAL', '5', true),
('GR', 'Греция', 'Greece', 'INTERNATIONAL', '3', true),
('GE', 'Грузия', 'Georgia', 'INTERNATIONAL', '3', true),
('DK', 'Дания', 'Denmark', 'INTERNATIONAL', '3', true),
('DJ', 'Джибути', 'Djibouti', 'INTERNATIONAL', '5', true),
('DM', 'Доминика', 'Dominica', 'INTERNATIONAL', '5', true),
('DO', 'Доминиканская Республика', 'Dominican Republic', 'INTERNATIONAL', '5', true),
('EG', 'Египет', 'Egypt', 'INTERNATIONAL', '5', true),
('ZM', 'Замбия', 'Zambia', 'INTERNATIONAL', '5', true),
('ZW', 'Зимбабве', 'Zimbabwe', 'INTERNATIONAL', '5', true),
('YE', 'Йемен', 'Yemen', 'INTERNATIONAL', '5', true),
('IL', 'Израиль', 'Israel', 'INTERNATIONAL', '3', true),
('IN', 'Индия', 'India', 'INTERNATIONAL', '3', true),
('ID', 'Индонезия', 'Indonesia', 'INTERNATIONAL', '4', true),
('JO', 'Иордания', 'Jordan', 'INTERNATIONAL', '4', true),
('IQ', 'Ирак', 'Iraq', 'INTERNATIONAL', '5', true),
('IR', 'Иран', 'Iran', 'INTERNATIONAL', '5', true),
('IE', 'Ирландия', 'Ireland', 'INTERNATIONAL', '3', true),
('IS', 'Исландия', 'Iceland', 'INTERNATIONAL', '3', true),
('ES', 'Испания', 'Spain', 'INTERNATIONAL', '3', true),
('IT', 'Италия', 'Italy', 'INTERNATIONAL', '3', true),
('CV', 'Кабо-Верде', 'Cape Verde', 'INTERNATIONAL', '5', true),
('KY', 'Каймановы о-ва', 'Cayman Islands', 'INTERNATIONAL', '5', true),
('KH', 'Камбоджа', 'Cambodia', 'INTERNATIONAL', '4', true),
('CM', 'Камерун', 'Cameroon', 'INTERNATIONAL', '5', true),
('CA', 'Канада', 'Canada', 'INTERNATIONAL', '4', true),
('QA', 'Катар', 'Qatar', 'INTERNATIONAL', '4', true),
('KE', 'Кения', 'Kenya', 'INTERNATIONAL', '5', true),
('CY', 'Кипр', 'Cyprus', 'INTERNATIONAL', '3', true),
('KI', 'Кирибати', 'Kiribati', 'INTERNATIONAL', '5', true),
('CO', 'Колумбия', 'Colombia', 'INTERNATIONAL', '5', true),
('CG', 'Конго', 'Congo', 'INTERNATIONAL', '5', true),
('CD', 'Конго (ДР)', 'DR Congo', 'INTERNATIONAL', '5', true),
('KP', 'Корея Северная', 'North Korea', 'INTERNATIONAL', '5', true),
('KR', 'Корея Южная', 'South Korea', 'INTERNATIONAL', '4', true),
('CR', 'Коста-Рика', 'Costa Rica', 'INTERNATIONAL', '5', true),
('CI', 'Кот-д''Ивуар', 'Cote d''Ivoire', 'INTERNATIONAL', '5', true),
('CU', 'Куба', 'Cuba', 'INTERNATIONAL', '5', true),
('KW', 'Кувейт', 'Kuwait', 'INTERNATIONAL', '4', true),
('LA', 'Лаос', 'Laos', 'INTERNATIONAL', '5', true),
('LV', 'Латвия', 'Latvia', 'INTERNATIONAL', '3', true),
('LS', 'Лесото', 'Lesotho', 'INTERNATIONAL', '5', true),
('LR', 'Либерия', 'Liberia', 'INTERNATIONAL', '5', true),
('LB', 'Ливан', 'Lebanon', 'INTERNATIONAL', '3', true),
('LY', 'Ливия', 'Libya', 'INTERNATIONAL', '5', true),
('LT', 'Литва', 'Lithuania', 'INTERNATIONAL', '3', true),
('LU', 'Люксембург', 'Luxembourg', 'INTERNATIONAL', '3', true),
('MU', 'Маврикий', 'Mauritius', 'INTERNATIONAL', '5', true),
('MR', 'Мавритания', 'Mauritania', 'INTERNATIONAL', '5', true),
('YT', 'Майотта', 'Mayotte', 'INTERNATIONAL', '5', true),
('MO', 'Макао (Китай)', 'Macau', 'INTERNATIONAL', '4', true),
('MK', 'Македония', 'North Macedonia', 'INTERNATIONAL', '3', true),
('MW', 'Малави', 'Malawi', 'INTERNATIONAL', '5', true),
('MY', 'Малайзия', 'Malaysia', 'INTERNATIONAL', '4', true),
('MV', 'Мальдивы', 'Maldives', 'INTERNATIONAL', '5', true),
('MT', 'Мальта', 'Malta', 'INTERNATIONAL', '3', true),
('MA', 'Марокко', 'Morocco', 'INTERNATIONAL', '5', true),
('MQ', 'Мартиника', 'Martinique', 'INTERNATIONAL', '5', true),
('MX', 'Мексика', 'Mexico', 'INTERNATIONAL', '5', true),
('MN', 'Монголия', 'Mongolia', 'INTERNATIONAL', '4', true),
('MS', 'Монтсеррат', 'Montserrat', 'INTERNATIONAL', '5', true),
('MM', 'Мьянма (Бирма)', 'Myanmar', 'INTERNATIONAL', '4', true),
('NA', 'Намибия', 'Namibia', 'INTERNATIONAL', '5', true),
('NR', 'Науру', 'Nauru', 'INTERNATIONAL', '5', true),
('NP', 'Непал', 'Nepal', 'INTERNATIONAL', '4', true),
('NE', 'Нигер', 'Niger', 'INTERNATIONAL', '5', true),
('NG', 'Нигерия', 'Nigeria', 'INTERNATIONAL', '5', true),
('NL', 'Нидерланды', 'Netherlands', 'INTERNATIONAL', '3', true),
('NI', 'Никарагуа', 'Nicaragua', 'INTERNATIONAL', '5', true),
('NZ', 'Новая Зеландия', 'New Zealand', 'INTERNATIONAL', '4', true),
('NC', 'Новая Каледония', 'New Caledonia', 'INTERNATIONAL', '5', true),
('NO', 'Норвегия', 'Norway', 'INTERNATIONAL', '3', true),
('KM', 'Коморские о-ва', 'Comoros', 'INTERNATIONAL', '5', true),
('SH', 'Остров Святой Елены', 'Saint Helena', 'INTERNATIONAL', '5', true),
('SB', 'Соломоновы о-ва', 'Solomon Islands', 'INTERNATIONAL', '5', true),
('OM', 'Оман', 'Oman', 'INTERNATIONAL', '4', true),
('PK', 'Пакистан', 'Pakistan', 'INTERNATIONAL', '4', true),
('PS', 'Палестина', 'Palestine', 'INTERNATIONAL', '5', true),
('PA', 'Панама', 'Panama', 'INTERNATIONAL', '5', true),
('PG', 'Папуа-Новая Гвинея', 'Papua New Guinea', 'INTERNATIONAL', '5', true),
('PY', 'Парагвай', 'Paraguay', 'INTERNATIONAL', '5', true),
('PE', 'Перу', 'Peru', 'INTERNATIONAL', '5', true),
('PN', 'Питкэрн', 'Pitcairn', 'INTERNATIONAL', '5', true),
('PF', 'Французская Полинезия', 'French Polynesia', 'INTERNATIONAL', '5', true),
('PL', 'Польша', 'Poland', 'INTERNATIONAL', '3', true),
('PT', 'Португалия', 'Portugal', 'INTERNATIONAL', '3', true),
('PR', 'Пуэрто-Рико', 'Puerto Rico', 'INTERNATIONAL', '5', true),
('RE', 'Реюньон', 'Reunion', 'INTERNATIONAL', '5', true),
('RW', 'Руанда', 'Rwanda', 'INTERNATIONAL', '5', true),
('RO', 'Румыния', 'Romania', 'INTERNATIONAL', '3', true),
('SV', 'Сальвадор', 'El Salvador', 'INTERNATIONAL', '5', true),
('WS', 'Самоа', 'Samoa', 'INTERNATIONAL', '5', true),
('ST', 'Сан-Томе и Принсипи', 'Sao Tome and Principe', 'INTERNATIONAL', '5', true),
('SA', 'Саудовская Аравия', 'Saudi Arabia', 'INTERNATIONAL', '4', true),
('SZ', 'Свазиленд', 'Eswatini', 'INTERNATIONAL', '5', true),
('SC', 'Сейшелы', 'Seychelles', 'INTERNATIONAL', '5', true),
('MF', 'Сен-Мартен', 'Saint Martin', 'INTERNATIONAL', '5', true),
('KN', 'Сент-Китс и Невис', 'Saint Kitts and Nevis', 'INTERNATIONAL', '5', true),
('VC', 'Сент-Винсент и Гренадины', 'Saint Vincent and the Grenadines', 'INTERNATIONAL', '5', true),
('LC', 'Сент-Люсия', 'Saint Lucia', 'INTERNATIONAL', '5', true),
('SG', 'Сингапур', 'Singapore', 'INTERNATIONAL', '4', true),
('SY', 'Сирия', 'Syria', 'INTERNATIONAL', '5', true),
('SK', 'Словакия', 'Slovakia', 'INTERNATIONAL', '3', true),
('SI', 'Словения', 'Slovenia', 'INTERNATIONAL', '3', true),
('SO', 'Сомали', 'Somalia', 'INTERNATIONAL', '5', true),
('SD', 'Судан', 'Sudan', 'INTERNATIONAL', '5', true),
('SR', 'Суринам', 'Suriname', 'INTERNATIONAL', '5', true),
('SL', 'Сьерра-Леоне', 'Sierra Leone', 'INTERNATIONAL', '5', true),
('TH', 'Таиланд', 'Thailand', 'INTERNATIONAL', '4', true),
('TZ', 'Танзания', 'Tanzania', 'INTERNATIONAL', '5', true),
('TL', 'Тимор-Лешти', 'Timor-Leste', 'INTERNATIONAL', '5', true),
('TG', 'Того', 'Togo', 'INTERNATIONAL', '5', true),
('TO', 'Тонга', 'Tonga', 'INTERNATIONAL', '5', true),
('TT', 'Тринидад и Тобаго', 'Trinidad and Tobago', 'INTERNATIONAL', '5', true),
('TV', 'Тувалу', 'Tuvalu', 'INTERNATIONAL', '5', true),
('TN', 'Тунис', 'Tunisia', 'INTERNATIONAL', '5', true),
('TM', 'Туркменистан', 'Turkmenistan', 'INTERNATIONAL', '1', true),
('TC', 'Теркс и Кайкос', 'Turks and Caicos', 'INTERNATIONAL', '5', true),
('UG', 'Уганда', 'Uganda', 'INTERNATIONAL', '5', true),
('UA', 'Украина', 'Ukraine', 'INTERNATIONAL', '3', true),
('WF', 'Уоллис и Футуна', 'Wallis and Futuna', 'INTERNATIONAL', '5', true),
('UY', 'Уругвай', 'Uruguay', 'INTERNATIONAL', '5', true),
('FJ', 'Фиджи', 'Fiji', 'INTERNATIONAL', '5', true),
('PH', 'Филиппины', 'Philippines', 'INTERNATIONAL', '4', true),
('FK', 'Фолклендские о-ва', 'Falkland Islands', 'INTERNATIONAL', '5', true),
('FR', 'Франция', 'France', 'INTERNATIONAL', '3', true),
('HR', 'Хорватия', 'Croatia', 'INTERNATIONAL', '3', true),
('CF', 'ЦАР', 'Central African Republic', 'INTERNATIONAL', '5', true),
('TD', 'Чад', 'Chad', 'INTERNATIONAL', '5', true),
('ME', 'Черногория', 'Montenegro', 'INTERNATIONAL', '3', true),
('CZ', 'Чехия', 'Czech Republic', 'INTERNATIONAL', '3', true),
('CL', 'Чили', 'Chile', 'INTERNATIONAL', '3', true),
('CH', 'Швейцария', 'Switzerland', 'INTERNATIONAL', '3', true),
('SE', 'Швеция', 'Sweden', 'INTERNATIONAL', '3', true),
('LK', 'Шри-Ланка', 'Sri Lanka', 'INTERNATIONAL', '4', true),
('EC', 'Эквадор', 'Ecuador', 'INTERNATIONAL', '5', true),
('GQ', 'Экваториальная Гвинея', 'Equatorial Guinea', 'INTERNATIONAL', '5', true),
('ER', 'Эритрея', 'Eritrea', 'INTERNATIONAL', '5', true),
('EE', 'Эстония', 'Estonia', 'INTERNATIONAL', '3', true),
('ET', 'Эфиопия', 'Ethiopia', 'INTERNATIONAL', '5', true),
('ZA', 'ЮАР', 'South Africa', 'INTERNATIONAL', '5', true),
('JP', 'Япония', 'Japan', 'INTERNATIONAL', '3', true);